/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package com.mybank.atm;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import mod2.domain.*;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.mybank.atm//atm//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "atmTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "com.mybank.atm.atmTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_atmAction",
        preferredID = "atmTopComponent"
)
@Messages({
    "CTL_atmAction=atm",
    "CTL_atmTopComponent=atm Window",
    "HINT_atmTopComponent=This is a atm window"
})
public final class atmTopComponent extends TopComponent {
    
    Bank bank;
    Customer currentCustomer;
    Account currentAccount;


    public atmTopComponent() {
        
        bank = Bank.getBank();

        Customer firstCustomer = new Customer("John", "Doe");
        Customer secondCustomer = new Customer("Jane", "Doe");

        SavingsAccount johnSavings = new SavingsAccount(1000, 7);
        CheckingAccount janeAccount = new CheckingAccount(500, 100);
        firstCustomer.addAccount(johnSavings);
        secondCustomer.addAccount(janeAccount);

        bank.addCustomer(firstCustomer);
        bank.addCustomer(secondCustomer);
        
        initComponents();
        setName(Bundle.CTL_atmTopComponent());
        setToolTipText(Bundle.HINT_atmTopComponent());
        
        for (Component c : jPanel3.getComponents()) {
            if ((c.getClass() == JButton.class) && !((((JButton) c).getText()).equals("ENTER"))) {
                JButton currentButton = (JButton) c;
                currentButton.addActionListener(new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        addDigit(e);
                    }
                    
                });
            }
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusFild = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        balanceButton = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        withdrowButton = new javax.swing.JButton();
        amountFild = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        pointButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyArea = new javax.swing.JTextArea();

        statusFild.setEditable(false);
        statusFild.setText(org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.statusFild.text")); // NOI18N

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        org.openide.awt.Mnemonics.setLocalizedText(balanceButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.balanceButton.text")); // NOI18N
        balanceButton.setEnabled(false);
        balanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceButtonActionPerformed(evt);
            }
        });
        jPanel2.add(balanceButton);

        org.openide.awt.Mnemonics.setLocalizedText(depositButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.depositButton.text")); // NOI18N
        depositButton.setEnabled(false);
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        jPanel2.add(depositButton);

        org.openide.awt.Mnemonics.setLocalizedText(withdrowButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.withdrowButton.text")); // NOI18N
        withdrowButton.setEnabled(false);
        withdrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrowButtonActionPerformed(evt);
            }
        });
        jPanel2.add(withdrowButton);

        amountFild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFildActionPerformed(evt);
            }
        });
        jPanel2.add(amountFild);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(4, 3));

        org.openide.awt.Mnemonics.setLocalizedText(oneButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.oneButton.text")); // NOI18N
        jPanel3.add(oneButton);

        org.openide.awt.Mnemonics.setLocalizedText(twoButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.twoButton.text")); // NOI18N
        jPanel3.add(twoButton);

        org.openide.awt.Mnemonics.setLocalizedText(threeButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.threeButton.text")); // NOI18N
        jPanel3.add(threeButton);

        org.openide.awt.Mnemonics.setLocalizedText(fourButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.fourButton.text")); // NOI18N
        jPanel3.add(fourButton);

        org.openide.awt.Mnemonics.setLocalizedText(fiveButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.fiveButton.text")); // NOI18N
        jPanel3.add(fiveButton);

        org.openide.awt.Mnemonics.setLocalizedText(sixButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.sixButton.text")); // NOI18N
        jPanel3.add(sixButton);

        org.openide.awt.Mnemonics.setLocalizedText(sevenButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.sevenButton.text")); // NOI18N
        jPanel3.add(sevenButton);

        org.openide.awt.Mnemonics.setLocalizedText(eightButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.eightButton.text")); // NOI18N
        jPanel3.add(eightButton);

        org.openide.awt.Mnemonics.setLocalizedText(nineButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.nineButton.text")); // NOI18N
        jPanel3.add(nineButton);

        org.openide.awt.Mnemonics.setLocalizedText(zeroButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.zeroButton.text")); // NOI18N
        jPanel3.add(zeroButton);

        org.openide.awt.Mnemonics.setLocalizedText(pointButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.pointButton.text")); // NOI18N
        jPanel3.add(pointButton);

        org.openide.awt.Mnemonics.setLocalizedText(enterButton, org.openide.util.NbBundle.getMessage(atmTopComponent.class, "atmTopComponent.enterButton.text")); // NOI18N
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        jPanel3.add(enterButton);

        jPanel1.add(jPanel3);

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        historyArea.setEditable(false);
        historyArea.setColumns(20);
        historyArea.setRows(5);
        jScrollPane1.setViewportView(historyArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void balanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceButtonActionPerformed
        // TODO add your handling code here:

        historyArea.append("Balance of " + currentCustomer.getFirstName() + "'s first account is $" + currentAccount.getBalance());
        if (currentAccount instanceof CheckingAccount) {
            historyArea.append(". This is Checking Account with overdraft protection $" + ((CheckingAccount) currentAccount).getOverdraftAmount() + "\n");
        } else {
            historyArea.append(". This is Savings Account with interest rate $" + ((SavingsAccount) currentAccount).getInterestRate() + "%\n");
        }
        statusFild.setText("READY");
    }//GEN-LAST:event_balanceButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        try {
            double amt = Double.parseDouble(amountFild.getText());

            currentAccount.deposit(amt);
            historyArea.append("Deposit: $" + amt + ", new balance is $" + currentAccount.getBalance() + "\n");
            statusFild.setText("READY");

        } catch (Exception e) {
            historyArea.append("ERROR: can't complete deposit operation!\n");
            statusFild.setText("ERROR");
        }
        amountFild.setText("");

    }//GEN-LAST:event_depositButtonActionPerformed

    private void withdrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrowButtonActionPerformed
        // TODO add your handling code here:
        try {
            double amt = Double.parseDouble(amountFild.getText());

            if (currentAccount.withdraw(amt)) {
                historyArea.append("Deposit: $" + amt + ", new balance is $" + currentAccount.getBalance() + "\n");
                statusFild.setText("READY");
            }

        } catch (OverdraftException ex) {
            historyArea.append("ERROR: Insuffisient funds!\n");
            statusFild.setText("ERROR");
        } catch (Exception e) {
            historyArea.append("ERROR: can't complete deposit operation!\n");
            statusFild.setText("ERROR");
        }
        amountFild.setText("");
    }//GEN-LAST:event_withdrowButtonActionPerformed

    private void amountFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFildActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_amountFildActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
        int customerID;

        try {
            historyArea.setText("");
            customerID = Integer.parseInt(amountFild.getText());

            currentCustomer = bank.getCustomer(customerID);
            currentAccount = currentCustomer.getAccount(0);
            historyArea.append("Customer with ID = " + customerID + " is " + currentCustomer.getLastName() + " " + currentCustomer.getFirstName() + "\n");
            balanceButton.setEnabled(true);
            depositButton.setEnabled(true);
            withdrowButton.setEnabled(true);
            enterButton.setEnabled(true);
        } catch (Exception e) {
            historyArea.append("ERROR: Customer not found or wrong Customer ID!\n");
        }
        amountFild.setText("");
        statusFild.setText("Customer: " + currentCustomer.getLastName() + " " + currentCustomer.getFirstName());

    }//GEN-LAST:event_enterButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountFild;
    private javax.swing.JButton balanceButton;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JTextArea historyArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton pointButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JTextField statusFild;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton withdrowButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    private void addDigit(ActionEvent evt) {
        // TODO add your handling code here:
        amountFild.setText(amountFild.getText() + ((JButton) evt.getSource()).getText());
    }
}
